### ISSUE TITLE
get error with new dataset

### ISSUE THREAD

**Issue by wentaoxandry** [georgesterpu/pyVSR#3]
Hi, @georgesterpu , 
I'm trying use your code extract aam features from a new dataset, but I got some error:
First is warning from menpo:
```
PycharmProjects/models/lib/python3.6/site-packages/menpofit/builder.py:338: MenpoFitModelBuilderWarning: The reference shape passed is not a TriMesh or subclass and therefore the reference frame (mask) will be calculated via a Delaunay triangulation. This may cause small triangles and thus suboptimal warps.
  MenpoFitModelBuilderWarning)
PycharmProjects/models/lib/python3.6/site-packages/menpo/image/boolean.py:711: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  copy.pixels[slices].flat = point_in_pointcloud(pointcloud, indices)
```
I want to ask if it is a problem for the later feature extraction?

then after a few times training I got the error like this:
```
PycharmProjects/models/lib/python3.6/site-packages/menpo/transform/homogeneous/scale.py:307: RuntimeWarning: divide by zero encountered in double_scalars
  UniformScale.__init__(self, target.norm() / source.norm(),
Traceback (most recent call last):
  File "/snap/pycharm-community/128/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/snap/pycharm-community/128/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/128/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/128/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/wentao/data1/pyVSRaam/example_aam.py", line 88, in <module>
    main()
  File "/media/wentao/data1/pyVSRaam/example_aam.py", line 59, in main
    output_dir='./features/aam_model/'
  File "/media/wentao/data1/pyVSRaam/pyVSR/avsr.py", line 47, in extract_save_features
    extractor.extract_save_features(files)
  File "/media/wentao/data1/pyVSRaam/pyVSR/Features/aam.py", line 286, in extract_save_features
    batch_size=None)
  File "PycharmProjects/models/lib/python3.6/site-packages/menpofit/aam/base.py", line 318, in increment
    batch_size=batch_size)
  File "PycharmProjects/models/lib/python3.6/site-packages/menpofit/aam/base.py", line 183, in _train
    verbose=verbose)
  File "PycharmProjects/models/lib/python3.6/site-packages/menpofit/aam/base.py", line 190, in _train_batch
    image_batch, group, self.reference_shape, verbose=verbose)
  File "PycharmProjects/models/lib/python3.6/site-packages/menpofit/builder.py", line 89, in rescale_images_to_reference_shape
    for i in wrap(images)]
  File "PycharmProjects/models/lib/python3.6/site-packages/menpofit/builder.py", line 89, in <listcomp>
    for i in wrap(images)]
  File "PycharmProjects/models/lib/python3.6/site-packages/menpo/image/base.py", line 2032, in rescale_to_pointcloud
    return_transform=return_transform)
  File "PycharmProjects/models/lib/python3.6/site-packages/menpo/image/base.py", line 1956, in rescale
    return_transform=return_transform)
  File "PycharmProjects/models/lib/python3.6/site-packages/menpo/image/base.py", line 1835, in warp_to_shape
    mode=mode, cval=cval)
  File "PycharmProjects/models/lib/python3.6/site-packages/menpo/image/interpolation.py", line 103, in cython_interpolation
    mode=mode, order=order, cval=cval))
  File "menpo/external/skimage/_warps_cy.pyx", line 118, in menpo.external.skimage._warps_cy._warp_fast
ValueError: negative dimensions are not allowed
```
I want to ask how can I deal with this error?
Thank you very much

**Comment by georgesterpu** [comment]
Hi @wentaoxandry 
I am not 100% sure about the triangulation warning, but I do remember seeing it for my own models and did not notice any problems.

Unfortunately, I do not have sufficient expertise to offer support with the menpo library. I highly recommend to create a minimalistic code snippet and report the problem upstream. Sorry !
